---
# We are currently using Oracle jvm.
# jvm creates a profile.d file, but some roles need to set up JAVA_HOME
# It would be necessary to edit those roles if jvm is changed.
# Roles that depend on java and setup JAVA_HOME:
# - tomcat

- name: add apt source ppa:webupd8team/java (oracle java (jdk))
  apt_repository: repo="ppa:webupd8team/java" state=present

- name: accept oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

# it stopped working because now oracle requires
# to accept the license before download
- name: install oracle jdk
  apt: name={{item}} state=present update-cache=yes cache_valid_time=3600
  with_items:
    - oracle-java7-set-default
    - oracle-java7-installer

- name: set java alternatives to use oracle jdk
  command: update-java-alternatives -s java-7-oracle

# XXX don't do this
# This conflicts with default-jre-headless package
#- name: create /usr/lib/jvm/default-java link
#  file: src=/usr/lib/jvm/java-7-oracle dest=default-java state=link
