---

#software versions
fedora_version: 4.4.1
tomcat_version: 7
java_version: 8

#tomcat user passwords
tomcat_user: tomcat
tomcat_password: password
fedora_admin_user: fedoraAdmin
fedora_admin_password: password

#fedora clustered
#Requires two or more hosts in inventory file
fedora_clustered: yes
